version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          AUTH0_CLIENT_ID: 123
          AUTH0_CLIENT_SECRET: secret
          AUTH0_CLIENT_DOMAIN: domain
          CALL_STRAVA_API:
          CONTACT_US_FORMAT:
          TEST_DATABASE_URL: mysql+pymysql://root:ubuntu@localhost/circle_test
      - image: circleci/mysql:5.7.26
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ubuntu
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: | 
            . venv/bin/activate
            pytest app/tests/test_activities.py
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

workflows:
  main:
    jobs:
      - build-and-test
