version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.7-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          AUTH0_CLIENT_ID: 123
          AUTH0_CLIENT_SECRET: secret
          AUTH0_CLIENT_DOMAIN: domain
          CALL_STRAVA_API:
          CONTACT_US_FORMAT:
          STRAVA_VERIFY_TOKEN:
          TEST_DATABASE_URL: mysql+pymysql://root:ubuntu@localhost/circle_test
      - image: circleci/mysql:5.7.26
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ubuntu
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
      - run:
          name: run tests and calculate coverage
          command: | 
            . venv/bin/activate
            coverage run -m pytest --junitxml="test-reports/results.xml"
            coverage xml
            coveralls --help
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: .coverage
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: test-reports/results.xml
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

workflows:
  main:
    jobs:
      - build-and-test
