"""empty message

Revision ID: 35697cae0c27
Revises: 6a31978f47a9
Create Date: 2020-05-28 07:22:41.572599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35697cae0c27'
down_revision = '6a31978f47a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_athlete',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.String(length=50), nullable=True),
    sa.Column('access_token_expires_at', sa.Integer(), nullable=True),
    sa.Column('access_token_expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strava_athlete')
    # ### end Alembic commands ###
