"""empty message

Revision ID: 6ea665fcec3e
Revises: 358470bc5e0f
Create Date: 2020-06-11 09:29:58.042553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea665fcec3e'
down_revision = '358470bc5e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('regular_activity', sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regular_activity', 'distance')
    op.drop_column('activity', 'distance')
    # ### end Alembic commands ###
