"""empty message

Revision ID: 6f43701fcd63
Revises: ff54bd00c7b6
Create Date: 2020-07-16 11:52:15.794291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f43701fcd63'
down_revision = 'ff54bd00c7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspiration', sa.Column('meta_og_description', sa.String(length=200), nullable=True))
    op.add_column('inspiration', sa.Column('meta_og_height', sa.Integer(), nullable=True))
    op.add_column('inspiration', sa.Column('meta_og_image', sa.String(length=200), nullable=True))
    op.add_column('inspiration', sa.Column('meta_og_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspiration', 'meta_og_width')
    op.drop_column('inspiration', 'meta_og_image')
    op.drop_column('inspiration', 'meta_og_height')
    op.drop_column('inspiration', 'meta_og_description')
    # ### end Alembic commands ###
