"""updated RegularActivity to store deleted ones

Revision ID: a07427d55292
Revises: b8836d118c80
Create Date: 2020-04-30 10:20:04.525040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07427d55292'
down_revision = 'b8836d118c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular_activity', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regular_activity', 'is_active')
    # ### end Alembic commands ###
