"""empty message

Revision ID: c95308cb18f8
Revises: 35697cae0c27
Create Date: 2020-06-01 07:21:35.039266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95308cb18f8'
down_revision = '35697cae0c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('local_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'local_timestamp')
    # ### end Alembic commands ###
