"""empty message

Revision ID: ff54bd00c7b6
Revises: 6e4ae57f9ef4
Create Date: 2020-07-14 11:13:21.618814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff54bd00c7b6'
down_revision = '6e4ae57f9ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_inspiration_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('inspiration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspiration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_inspiration_likes')
    # ### end Alembic commands ###
